### ISSUE TITLE
Use GET as default method

### ISSUE THREAD

**Issue by gpbl** [yahoo/routr#15]
Most (if not all) my routes are `get` routes. Is it possible to skip the `method` property and make it defaults to `get`?

**Comment by lingyan** [comment]
@gpbl Thanks for the feedback.  IMO, it is better to be more explicit in this case though, so that there is no black magic behind the scene, and everyone knows exactly which method is supported for each route.

**Comment by gpbl** [comment]
OK yes I can understand! Thanks for the answer :-)

**Comment by bsr203** [comment]
I came here to raise an issue for the same :-) but, when do one use a non-get request for routing. I also don't see a way to alter `METHODS` supported

**Comment by lingyan** [comment]
@bsr203 There could be POST requests for form submission like use cases.

`METHODS` is only used for defining method constants.  Only GET is being used for the default method value, if `getRoute()` is called without method specified.  Could you give me some more info on why you want to alter it?  Thanks!

**Comment by bsr203** [comment]
@lingyan my ignorance. I only use ajax request for api request and didn't think about other scenario. Thanks for clarifying.

**Comment by lingyan** [comment]
@bsr203 No problem at all.  Thanks for your input!
