### ISSUE TITLE
Router config method is case sensitive

### ISSUE THREAD

**Issue by jhwang09** [yahoo/routr#21]
In Router.js, line 38

method === this.config.method

this is case sensitive so it will fail if the pass in method and the config.method are not exactly the same (ignore case)

**Comment by lingyan** [comment]
@jhwang09 Thanks for reporting.  Fixed in 0.1.1: https://github.com/yahoo/routr/releases/tag/v0.1.1

**Comment by awu1986** [comment]
:+1:
