### ISSUE TITLE
Persist routes between page refreshes?

### ISSUE THREAD

**Issue by JoshuaGross** [yahoo/routr#25]
Is there any plan to support persistent routes between page refreshes (or is it deliberately not supported)?

To be specific, in the fluxible.io example, navigation between Home/About works properly and navigating to `/` or `/about` works as expected, but if you click on Home/About and then refresh the page, you may be directed to another page because the URL doesn't change to reflect your navigation. It should be fairly trivial to persist navigation using a hash, and I'd be happy to implement something unless this has already been done or there's a compelling reason not to.

**Comment by redonkulus** [comment]
That is more likely a bug or lack of implementation in the example. On the actual fluxible.io site, this works as expected. Click Quick Start button on the homepage, then refresh the page, you should still be on the Quick Start page.

**Comment by JoshuaGross** [comment]
Noted, fixed in this PR: https://github.com/yahoo/generator-fluxible/pull/20

Thanks!
