### ISSUE TITLE
Route Order

### ISSUE THREAD

**Issue by sebslomski** [yahoo/routr#28]
Hi,

is routr capable of handling the order/weight of the routes?

e.g.:
```javascript
{
  landingPage: {
    path: '/:slug',
    method: 'get',
    page: 'landingPage'
  },
  members: {
    path: '/members',
    method: 'get',
    page: 'members'
  }
}
```

This example is not working, the route matches always for `landingPage`.
If I reorder them and put `members` before `landingPage`, it's working. But according to http://stackoverflow.com/questions/5525795/does-javascript-guarantee-object-property-order I don't want to rely on the order.

Is there a way to handle this in routr?

**Comment by mridgway** [comment]
Route order is indeed based on object key order as declared right now. This is something that should be fixed with a preference of passing an array instead an object. The name would become a key in the route object.
